# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-17 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('librari', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('year', models.IntegerField(max_length=5)),
                ('copies', models.IntegerField(max_length=10)),
            ],
        ),
    ]
