# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-17 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs_id', models.IntegerField(max_length=3)),
                ('borrow_date', models.CharField(max_length=100)),
                ('item_id', models.IntegerField(max_length=3)),
                ('return_date', models.CharField(max_length=100)),
                ('fee', models.IntegerField(max_length=10)),
            ],
        ),
    ]
